Added a warning message to bash scripts when user has no java version set

diff --git a/bin/csvloader b/bin/csvloader
--- a/bin/csvloader
+++ b/bin/csvloader
@@ -91,6 +91,9 @@ fi
 if [ "$JAVA_HOME" != "" ]; then
   #echo "run java in $JAVA_HOME"
   JAVA=$JAVA_HOME/bin/java
+else
+  echo "Couldn't find java version to run (make sure JAVA_HOME is set)."
+  exit 1
 fi
 
 # check envvars to see if a user overrides log4j conf
diff --git a/bin/sqlcmd b/bin/sqlcmd
--- a/bin/sqlcmd
+++ b/bin/sqlcmd
@@ -87,6 +87,9 @@ JAVA_HEAP_MAX=-Xmx256m
 if [ "$JAVA_HOME" != "" ]; then
   #echo "run java in $JAVA_HOME"
   JAVA=$JAVA_HOME/bin/java
+else
+  echo "Couldn't find java version to run (make sure JAVA_HOME is set)."
+  exit 1
 fi
 
 # check envvars to see if a user overrides log4j conf
diff --git a/bin/voltdb3 b/bin/voltdb3
--- a/bin/voltdb3
+++ b/bin/voltdb3
@@ -75,6 +75,9 @@ JAVA=`which java`
 if [ "$JAVA_HOME" != "" ]; then
   #echo "run java in $JAVA_HOME"
   JAVA=$JAVA_HOME/bin/java
+else
+  echo "Couldn't find java version to run (make sure JAVA_HOME is set)."
+  exit 1
 fi
 
 # JVM detection taken from Apache Cassandra
