Working on ENG-1666, the down with ant stuff. 1) Update version numbers to 2.0. Still need to not have to do this. 2) Allow for log4j config and use the default one. 3) Use what seems like the right java command line for the server. 4) Update the readmes that mention ant to mention make. 5) Remove mentions of hadoop. 6) Remove some code that wasn't run (the VOLTDB_CONF_DIR stuff)

diff --git a/bin/exporttofile b/bin/exporttofile
--- a/bin/exporttofile
+++ b/bin/exporttofile
@@ -22,31 +22,28 @@ script=`basename "$this"`
 bin=`cd "$bin"; pwd`
 this="$bin/$script"
 
-# the root of the Hadoop installation
+# the root of the VoltDB installation
 export VOLTDB_HOME=`dirname "$this"`/..
 
-#check to see if the conf dir is given as an optional argument
-if [ $# -gt 1 ]
-then
-    if [ "--config" = "$1" ]
-	  then
-	      shift
-	      confdir=$1
-	      shift
-	      VOLTDB_CONF_DIR=$confdir
-    fi
-fi
-
-# Allow alternate conf dir location.
-VOLTDB_CONF_DIR="${VOLTDB_CONF_DIR:-$VOLTDB_HOME/conf}"
-
 JAVA=`which java`
-JAVA_HEAP_MAX=-Xmx1024m
+JAVA_HEAP_MAX=-Xmx512m
 
 # some Java parameters
 if [ "$JAVA_HOME" != "" ]; then
   #echo "run java in $JAVA_HOME"
   JAVA=$JAVA_HOME/bin/java
+fi
+
+# check envvars to see if a user overrides log4j conf
+if [ -n "${LOG4J_CONFIG_PATH:-x}" ]; then
+  if [ -f "$VOLTDB_HOME/src/frontend/log4j.xml" ]; then
+    LOG4J_CONFIG_PATH=$VOLTDB_HOME/src/frontend/log4j.xml
+  elif [ -f "$VOLTDB_HOME/voltdb/log4j.xml" ]; then
+    LOG4J_CONFIG_PATH=$VOLTDB_HOME/voltdb/log4j.xml
+  else
+    echo "Couldn't find log4j configuration file."
+    exit 1
+  fi
 fi
 
 if [ -d "$VOLTDB_HOME/obj/release/prod" ]; then
@@ -59,8 +56,8 @@ elif [ -d "$VOLTDB_HOME/obj/debug/prod" ]; then
   for f in $VOLTDB_HOME/third_party/java/jars/*.jar; do
     CLASSPATH=${CLASSPATH}:$f;
   done
-elif [ -f "$VOLTDB_HOME/voltdb/voltdb-1.3.6.jar" ]; then
-  CLASSPATH=$VOLTDB_HOME/voltdb/voltdb-1.3.6.jar
+elif [ -f "$VOLTDB_HOME/voltdb/voltdb-2.0.jar" ]; then
+  CLASSPATH=$VOLTDB_HOME/voltdb/voltdb-2.0.jar
 else
   echo "Couldn't find compiled VoltDB to run."
   exit 1
@@ -74,6 +71,7 @@ done
 CLASSPATH=${CLASSPATH}:${EXTRA_CLASSPATH}
 
 # run it
-export CMDVAL="$JAVA -Xmx512m $VOLTDB_OPTS -classpath $CLASSPATH org.voltdb.export.ExportToFileClient $@"
+export CMDVAL="$JAVA -Xmx512m $VOLTDB_OPTS -Dlog4j.configuration=file://${LOG4J_CONFIG_PATH} "
+export CMDVAL=$CMDVAL"-classpath $CLASSPATH org.voltdb.exportclient.ExportToFileClient $@"
 #echo $CMDVAL
 exec $CMDVAL
diff --git a/bin/voltdb b/bin/voltdb
--- a/bin/voltdb
+++ b/bin/voltdb
@@ -22,28 +22,9 @@ script=`basename "$this"`
 bin=`cd "$bin"; pwd`
 this="$bin/$script"
 
-# the root of the Hadoop installation
+# the root of the VoltDB installation
 export VOLTDB_HOME=`dirname "$this"`/..
 #echo $VOLTDB_HOME
-
-#check to see if the conf dir is given as an optional argument
-if [ $# -gt 1 ]
-then
-    if [ "--config" = "$1" ]
-	  then
-	      shift
-	      confdir=$1
-	      shift
-	      VOLTDB_CONF_DIR=$confdir
-    fi
-fi
-
-# Allow alternate conf dir location.
-VOLTDB_CONF_DIR="${VOLTDB_CONF_DIR:-$VOLTDB_HOME/conf}"
-
-# get arguments
-#COMMAND=$1
-#shift
 
 JAVA=`which java`
 JAVA_HEAP_MAX=-Xmx1024m
@@ -55,13 +36,25 @@ if [ "$JAVA_HOME" != "" ]; then
 fi
 
 # check envvars which might override default args
-if [ "$VOLTDB_HEAPSIZE" != "" ]; then
-  #echo "run with heapsize $HADOOP_HEAPSIZE"
+if [ -n "${VOLTDB_HEAPSIZE:+x}" ]; then
+  #echo "run with heapsize $VOLTDB_HEAPSIZE"
   JAVA_HEAP_MAX="-Xmx""$VOLTDB_HEAPSIZE""m"
 else
   JAVA_HEAP_MAX="-Xmx1024m"
 fi
 #echo $JAVA_HEAP_MAX
+
+# check envvars to see if a user overrides log4j conf
+if [ -n "${LOG4J_CONFIG_PATH:-x}" ]; then
+  if [ -f "$VOLTDB_HOME/src/frontend/log4j.xml" ]; then
+    LOG4J_CONFIG_PATH=$VOLTDB_HOME/src/frontend/log4j.xml
+  elif [ -f "$VOLTDB_HOME/voltdb/log4j.xml" ]; then
+    LOG4J_CONFIG_PATH=$VOLTDB_HOME/voltdb/log4j.xml
+  else
+    echo "Couldn't find log4j configuration file."
+    exit 1
+  fi
+fi
 
 if [ -d "$VOLTDB_HOME/obj/release/prod" ]; then
   CLASSPATH=$VOLTDB_HOME/obj/release/prod:$VOLTDB_HOME/third_party/java/obj
@@ -73,8 +66,8 @@ elif [ -d "$VOLTDB_HOME/obj/debug/prod" ]; then
   for f in $VOLTDB_HOME/third_party/java/jars/*.jar; do
     CLASSPATH=${CLASSPATH}:$f;
   done
-elif [ -f "$VOLTDB_HOME/voltdb/voltdb-1.3.6.jar" ]; then
-  CLASSPATH=$VOLTDB_HOME/voltdb/voltdb-1.3.6.jar
+elif [ -f "$VOLTDB_HOME/voltdb/voltdb-2.0.jar" ]; then
+  CLASSPATH=$VOLTDB_HOME/voltdb/voltdb-2.0.jar
 else
   echo "Couldn't find compiled VoltDB to run."
   exit 1
@@ -96,6 +89,10 @@ for f in $VOLTDB_HOME/lib/*.jar; do
 done
 
 # run it
-export CMDVAL="$JAVA $JAVA_HEAP_MAX $VOLTDB_OPTS -Djava.library.path=${JAVA_LIBRARY_PATH} -classpath $CLASSPATH org.voltdb.VoltDB $@"
+export CMDVAL="$JAVA -server -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp "
+export CMDVAL=$CMDVAL"-XX:-ReduceInitialCardMarks $JAVA_HEAP_MAX $VOLTDB_OPTS "
+export CMDVAL=$CMDVAL"-Dlog4j.configuration=file://${LOG4J_CONFIG_PATH} "
+export CMDVAL=$CMDVAL"-Djava.library.path=${JAVA_LIBRARY_PATH} -classpath $CLASSPATH "
+export CMDVAL=$CMDVAL"org.voltdb.VoltDB $@"
 #echo $CMDVAL
 exec $CMDVAL
