ENG-9831 set classpath for kafkaloader

diff --git a/bin/kafkaloader8 b/bin/kafkaloader8
--- a/bin/kafkaloader8
+++ b/bin/kafkaloader8
@@ -88,6 +88,8 @@ then
     JAVA_HEAP_MAX=-Xmx2048m
 fi
 
+BUNDLES_DIR=$VOLTDB_HOME/bundles
+
 # some Java parameters
 if [ "$JAVA_HOME" != "" ]; then
   #echo "run java in $JAVA_HOME"
@@ -119,6 +121,14 @@ else
   exit 1
 fi
 
+# add kakfka jar file to classpath
+KAFKA_LOADER_BUNDLE=${BUNDLES_DIR}/kafkastream.jar
+if [ ! -f ${KAFKA_LOADER_BUNDLE} ]; then
+  echo "Couldn't find kafka jar file."
+  exit 1
+fi
+CLASSPATH=${CLASSPATH}:${KAFKA_LOADER_BUNDLE};
+
 # add libs to CLASSPATH
 for f in $VOLTDB_LIB/*.jar; do
   CLASSPATH=${CLASSPATH}:$f;
@@ -133,6 +143,6 @@ done
 
 # run it
 export CMDVAL="$JAVA -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.awt.headless=true $JAVA_HEAP_MAX $VOLTDB_OPTS -Dlog4j.configuration=file://${LOG4J_CONFIG_PATH} "
-export CMDVAL=$CMDVAL"-classpath $CLASSPATH org.voltdb.importclient.kafka.KafkaExternalLoader"
+export CMDVAL=$CMDVAL"-classpath $CLASSPATH org.voltdb.importclient.kafka.KafkaLoader"
 #echo $CMDVAL "$@"
 exec $CMDVAL "$@"
