Finishing ENG-1666: Create a script to start VoltDB and VoltCompiler with single commands (down with Ant)
Added license and listed important ENV vars at the top of the 4 scripts. Tweaked a few tiny things. Also updated the usage message for VoltCompiler.

diff --git a/bin/sqlcommand b/bin/sqlcommand
--- a/bin/sqlcommand
+++ b/bin/sqlcommand
@@ -1,5 +1,58 @@
 #!/usr/bin/env bash
 
+# This file is part of VoltDB.
+
+# Copyright (C) 2008-2011 VoltDB Inc.
+#
+# This file contains original code and/or modifications of original code.
+# Any modifications made by VoltDB Inc. are licensed under the following
+# terms and conditions:
+#
+# Permission is hereby granted, free of charge, to any person obtaining
+# a copy of this software and associated documentation files (the
+# "Software"), to deal in the Software without restriction, including
+# without limitation the rights to use, copy, modify, merge, publish,
+# distribute, sublicense, and/or sell copies of the Software, and to
+# permit persons to whom the Software is furnished to do so, subject to
+# the following conditions:
+#
+# The above copyright notice and this permission notice shall be
+# included in all copies or substantial portions of the Software.
+
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
+# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
+# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
+# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
+# OTHER DEALINGS IN THE SOFTWARE.
+
+# Original license for parts of this script copied from or influenced by
+# the Hadoop startup script:
+#
+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements.  See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License.  You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+
+# The VoltDB SQL Command line start script
+#
+# Environment Variables
+#   JAVA_HOME        The java implementation to use.  Overrides JAVA_HOME.
+#   LOG4J_CONFIG_PATH     Path to alternate log4j configuration
+
+
 bin=`dirname "$0"`
 bin=`cd "$bin"; pwd`
 
@@ -34,6 +87,18 @@ if [ "$JAVA_HOME" != "" ]; then
   JAVA=$JAVA_HOME/bin/java
 fi
 
+# check envvars to see if a user overrides log4j conf
+if [ -n "${LOG4J_CONFIG_PATH:-x}" ]; then
+  if [ -f "$VOLTDB_HOME/src/frontend/log4j.xml" ]; then
+    LOG4J_CONFIG_PATH=$VOLTDB_HOME/src/frontend/log4j.xml
+  elif [ -f "$VOLTDB_HOME/voltdb/log4j.xml" ]; then
+    LOG4J_CONFIG_PATH=$VOLTDB_HOME/voltdb/log4j.xml
+  else
+    echo "Couldn't find log4j configuration file."
+    exit 1
+  fi
+fi
+
 VOLTDBJAR=`ls $VOLTDB_HOME/voltdb/voltdb-2.*.jar`
 if [ -n "${VOLTDBJAR:+x}" ]; then
   CLASSPATH=$VOLTDBJAR
@@ -48,6 +113,7 @@ for f in $VOLTDB_HOME/lib/*.jar; do
 done
 
 # run it
-export CMDVAL="$JAVA -Xmx512m -classpath $CLASSPATH org.voltdb.utils.SQLCommand $@"
+export CMDVAL="$JAVA -Xmx512m -Dlog4j.configuration=file://${LOG4J_CONFIG_PATH} "
+export CMDVAL=$CMDVAL"-classpath $CLASSPATH org.voltdb.utils.SQLCommand $@"
 #echo $CMDVAL
 exec $CMDVAL
